{
 "title": "PCC",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "pccguid", "query": "pccguidvalue" }
  ]
 },
 "panels": [
  {
   "title": "SI Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "serviceinstance_UsedHeapSize{source_id=~\"$pccguid\"}",
     "legendFormat": "Heap Used"
    },
    {
     "expr": "serviceinstance_TotalHeapSize{source_id=~\"$pccguid\"}",
     "legendFormat": "Heap Total"
    }
   ]
  },
  {
   "title": "Member Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "member_MaxMemory{source_id=~\"$pccguid\"}",
     "legendFormat": "Member Max Memory "
    },
    {
     "expr": "member_UsedMemory{source_id=~\"$pccguid\"}",
     "legendFormat": "Member Used Memory "
    },
    {
     "expr": "member_CurrentHeapSize{source_id=~\"$pccguid\"}",
     "legendFormat": "Member Heap Size"
    }
   ]
  },
  {
   "title": "Member Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "member_BytesReceivedRate{source_id=~\"$pccguid\"}",
     "legendFormat": "Member Received Data Rate"
    },
    {
     "expr": "member_BytesSentRate{source_id=~\"$pccguid\"}",
     "legendFormat": "Member Sent Data Rate "
    }
   ]
  },
  {
   "title": "Member Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 10 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "member_GetsAvgLatency{source_id=~\"$pccguid\"}",
     "legendFormat": "Member GET Average Latency"
    },
    {
     "expr": "member_PutsAvgLatency{source_id=~\"$pccguid\"}",
     "legendFormat": "Member PUT Average Latency"
    }
   ]
  },
  {
   "title": "Member Stats",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "member_CreatesRate{source_id=~\"$pccguid\"}",
     "legendFormat": "Creates Rate"
    },
    {
     "expr": "member_DeserializationRate{source_id=~\"$pccguid\"}",
     "legendFormat": "Deserialization Rate"
    },
    {
     "expr": "member_DestroysRate{source_id=~\"$pccguid\"}",
     "legendFormat": "Destroys Rate"
    },
    {
     "expr": "member_FunctionExecutionRate{source_id=~\"$pccguid\"}",
     "legendFormat": "Function Executions Rate"
    },
    {
     "expr": "member_JVMPauses{source_id=~\"$pccguid\"}",
     "legendFormat": "JVMPauses"
    },
    {
     "expr": "member_PDXDeserializationRate{source_id=~\"$pccguid\"}",
     "legendFormat": "PDX Deserialization Rate"
    },
    {
     "expr": "member_PutAllRate{source_id=~\"$pccguid\"}",
     "legendFormat": "Put All Rate"
    },
    {
     "expr": "member_PutRequestRate{source_id=~\"$pccguid\"}",
     "legendFormat": "Put Request Rate"
    },
    {
     "expr": "member_PutsRate{source_id=~\"$pccguid\"}",
     "legendFormat": "Puts Rate"
    }
   ]
  },
  {
   "title": "Member Performance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "member_AverageReads{source_id=~\"$pccguid\"}",
     "legendFormat": "Member Average Reads"
    },
    {
     "expr": "member_AverageWrites{source_id=~\"$pccguid\"}",
     "legendFormat": "Member Average Writes"
    },
    {
     "expr": "member_GetRequestRate{source_id=~\"$pccguid\"}",
     "legendFormat": "Member Get Rate"
    },
    {
     "expr": "member_PutRequestRate{source_id=~\"$pccguid\"}",
     "legendFormat": "Member Put Rate"
    },
    {
     "expr": "member_FunctionExecutionRate{source_id=~\"$pccguid\"}",
     "legendFormat": "Member Function Exec Rate"
    }
   ]
  },
  {
   "title": "SI Unused Heap %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "serviceinstance_UnusedHeapSizePercentage{source_id=~\"$pccguid\"}",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Members",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "serviceinstance_MemberCount{source_id=~\"$pccguid\"}",
     "legendFormat": "_"
    }
   ]
  },
  {
   "title": "Regions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "serviceinstance_TotalRegionCount{source_id=~\"$pccguid\"}",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Member Used Memory %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "member_UsedMemoryPercentage{source_id=~\"$pccguid\"}",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Member Total Buckets",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 11, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "member_TotalBucketCount{source_id=~\"$pccguid\"}",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Member Uptime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "member_MemberUpTime{source_id=~\"$pccguid\"}",
     "legendFormat": "_"
    }
   ]
  },
  {
   "title": "Disk Write Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "diskstore_DiskWritesAvgLatency{source_id=~\"$pccguid\"}",
     "legendFormat": "Avg Write Latency"
    }
   ]
  },
  {
   "title": "Member FD Limit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "member_FileDescriptorLimit{source_id=~\"$pccguid\"}",
     "legendFormat": "_"
    }
   ]
  },
  {
   "title": "Usable Disk Space",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "diskstore_UsableSpace{source_id=~\"$pccguid\"}",
     "legendFormat": "Bytes"
    },
    {
     "expr": "diskstore_TotalSpace{source_id=~\"$pccguid\"}",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Disk Total Space",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "diskstore_TotalSpace{source_id=~\"$pccguid\"}",
     "legendFormat": "_"
    }
   ]
  },
  {
   "title": "Member Reply Waits in Progress",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "member_ReplyWaitsInProgress{source_id=~\"$pccguid\"}",
     "legendFormat": "Ops"
    }
   ]
  },
  {
   "title": "Member Threads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "member_NumThreads{source_id=~\"$pccguid\"}",
     "legendFormat": "_"
    }
   ]
  },
  {
   "title": "Member FDs Remaining",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "member_FileDescriptorRemaining{source_id=~\"$pccguid\"}",
     "legendFormat": "FDs"
    }
   ]
  },
  {
   "title": "SI Running Functions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "serviceinstance_NumRunningFunctions{source_id=~\"$pccguid\"}",
     "legendFormat": "Running Function Count"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 65 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "member_JVMPauses{source_id=~\"$pccguid\"}",
     "legendFormat": "JVM Pauses/second"
    }
   ]
  },
  {
   "title": "Gateway Receiver",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "gatewayReceiver_EventsReceivedRate{source_id=~\"$pccguid\"}",
     "legendFormat": "events/second"
    }
   ]
  },
  {
   "title": "Member Stats II",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 11, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "member_ClientConnectionCount{source_id=~\"$pccguid\"}",
     "legendFormat": "Member Client Connection Count"
    },
    {
     "expr": "member_GarbageCollectionCount{source_id=~\"$pccguid\"}",
     "legendFormat": "Member GCs Count"
    },
    {
     "expr": "member_TotalFileDescriptorOpen{source_id=~\"$pccguid\"}",
     "legendFormat": "Member FDs Open"
    },
    {
     "expr": "member_TotalHitCount{source_id=~\"$pccguid\"}",
     "legendFormat": "Member Total Hit Count"
    },
    {
     "expr": "member_TotalMissCount{source_id=~\"$pccguid\"}",
     "legendFormat": "Member Total Miss Count"
    },
    {
     "expr": "member_TotalPrimaryBucketCount{source_id=~\"$pccguid\"}",
     "legendFormat": "Member Total Primary Bucket Count"
    }
   ]
  },
  {
   "title": "System",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "member_HostCpuUsage{source_id=~\"$pccguid\"}",
     "legendFormat": "Member CPU Usage"
    }
   ]
  },
  {
   "title": "RegionX Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "region__regionX_CreatesRate{source_id=~\"$pccguid\"}",
     "legendFormat": "Creates Per Second"
    },
    {
     "expr": "region__regionX_DestroyRate{source_id=~\"$pccguid\"}",
     "legendFormat": "Destroys Per Second"
    },
    {
     "expr": "region__regionX_GetsRate{source_id=~\"$pccguid\"}",
     "legendFormat": "Gets Per Second"
    },
    {
     "expr": "region__regionX_PutsRate{source_id=~\"$pccguid\"}",
     "legendFormat": "Puts Per Second"
    },
    {
     "expr": "region__regionX_PutAllRate{source_id=~\"$pccguid\"}",
     "legendFormat": "PutAlls Per Second"
    },
    {
     "expr": "region__regionX_PutLocalRate{source_id=~\"$pccguid\"}",
     "legendFormat": "PutLocals Per Second"
    },
    {
     "expr": "region__regionX_PutRemoteRate{source_id=~\"$pccguid\"}",
     "legendFormat": "PutRemotes Per Second"
    }
   ]
  },
  {
   "title": "RegionX Stats II",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "region__regionX_EntrySize{source_id=~\"$pccguid\"}",
     "legendFormat": "Entry Size"
    }
   ]
  },
  {
   "title": "RegionX Bucket Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "region__regionX_BucketCount{source_id=~\"$pccguid\"}",
     "legendFormat": "Buckets"
    },
    {
     "expr": "region__regionX_PrimaryBucketCount{source_id=~\"$pccguid\"}",
     "legendFormat": "Primary-Buckets"
    }
   ]
  }
 ]
}